#!/bin/sh
set -e

. /usr/lib/smhub/service-helpers.sh

PKG_NAME="connecta-m-hi"
SERVICE_NAME="dom.oti.cat"

echo "[oticonnect] postinst start"

pkg_openrc_install "${PKG_NAME}" "${SERVICE_NAME}" "install"
pkg_service_restart "${PKG_NAME}" "${SERVICE_NAME}"

echo "[oticonnect] postinst done"
exit 0

