#!/bin/sh
set -e

. /usr/lib/smhub/service-helpers.sh

PKG_NAME="connecta-m-hi"
SERVICE_NAME="dom.oti.cat"

echo "[oticonnect] prerm: stopping service..."
pkg_service_stop "${PKG_NAME}" "${SERVICE_NAME}"

exit 0

